### ISSUE TITLE
找不到语料下载链接

### ISSUE THREAD

**Issue by laubonghaudoi** [crownpku/Somiao-Pinyin#2]
请问[这个页面](http://wortschatz.uni-leipzig.de/en/download/)里哪里有下载中文语料？

**Comment by crownpku** [comment]
在english german等等一堆语言旁边有一个more的button，从那里点击进去。

**Comment by laubonghaudoi** [comment]
点进去后发现有这么多个下载选项，是随便哪一个都可以吗？
![image](https://user-images.githubusercontent.com/11172180/30773077-c0bccfec-a09b-11e7-829b-c6c5dc6f8a1e.png)

**Comment by crownpku** [comment]
用1M那个，语料自然是越多越好。
